package com.moonspace.adminfinanciera.core.ui.theme

import androidx.compose.ui.graphics.Color

object FinanceColors {
    val Primary = Color(0xFF1E6B57)
    val OnPrimary = Color(0xFFFFFFFF)
    val PrimaryContainer = Color(0xFFD5EEE4)
    val OnPrimaryContainer = Color(0xFF123A2E)
    val Secondary = Color(0xFF3D5F79)
    val Background = Color(0xFFF6F8F5)
    val Surface = Color(0xFFFFFFFF)
    val SurfaceVariant = Color(0xFFE8EEEA)
    val OnSurface = Color(0xFF17221C)
    val OnSurfaceVariant = Color(0xFF45534C)
    val Outline = Color(0xFF718078)
    val OutlineVariant = Color(0xFFD2DBD5)
    val Success = Color(0xFF176B48)
    val SuccessContainer = Color(0xFFDFF3E8)
    val Expense = Color(0xFFB42318)
    val ExpenseContainer = Color(0xFFFDE7E5)
    val Warning = Color(0xFF845500)
    val WarningContainer = Color(0xFFFFF1CC)
    val Info = Color(0xFF275D9F)
    val InfoContainer = Color(0xFFE7F0FC)

    val DarkPrimary = Color(0xFF8DD7B9)
    val DarkOnPrimary = Color(0xFF07382D)
    val DarkPrimaryContainer = Color(0xFF174E3D)
    val DarkOnPrimaryContainer = Color(0xFFD1F3E4)
    val DarkSecondary = Color(0xFFA9C7E2)
    val DarkBackground = Color(0xFF101713)
    val DarkSurface = Color(0xFF171F1A)
    val DarkSurfaceVariant = Color(0xFF202B24)
    val DarkOnSurface = Color(0xFFEAF2EC)
    val DarkOnSurfaceVariant = Color(0xFFBDCAC1)
    val DarkOutline = Color(0xFF89988E)
    val DarkOutlineVariant = Color(0xFF3B4940)
    val DarkSuccess = Color(0xFF72D5A6)
    val DarkSuccessContainer = Color(0xFF173B2B)
    val DarkExpense = Color(0xFFFF8D82)
    val DarkExpenseContainer = Color(0xFF4B201E)
    val DarkWarning = Color(0xFFFFD166)
    val DarkWarningContainer = Color(0xFF493716)
    val DarkInfo = Color(0xFF9CC5FF)
    val DarkInfoContainer = Color(0xFF1E3553)
}
