package com.moonspace.adminfinanciera.core.ui.theme

import androidx.compose.ui.graphics.Color

object FinanceColors {
    val Primary = Color(0xFF09637E)
    val OnPrimary = Color(0xFFFFFFFF)
    val PrimaryContainer = Color(0xFF7AB2B2)
    val OnPrimaryContainer = Color(0xFF123B46)
    val Secondary = Color(0xFF088395)
    val Background = Color(0xFFEBF4F6)
    val Surface = Color(0xFFFFFFFF)
    val SurfaceVariant = Color(0xFFDDEBED)
    val OnSurface = Color(0xFF17343D)
    val OnSurfaceVariant = Color(0xFF435E66)
    val Outline = Color(0xFF66868C)
    val OutlineVariant = Color(0xFFC9DCDF)
    val Success = Color(0xFF176B48)
    val SuccessContainer = Color(0xFFDFF3E8)
    val OnSuccessContainer = Color(0xFF123A2E)
    val Expense = Color(0xFFB42318)
    val ExpenseContainer = Color(0xFFFDE7E5)
    val OnExpenseContainer = Color(0xFF62130D)
    val Warning = Color(0xFF845500)
    val WarningContainer = Color(0xFFFFF1CC)
    val OnWarningContainer = Color(0xFF493716)
    val Info = Color(0xFF275D9F)
    val InfoContainer = Color(0xFFE7F0FC)
    val OnInfoContainer = Color(0xFF163B67)

    val DarkPrimary = Color(0xFF7AB2B2)
    val DarkOnPrimary = Color(0xFF102F38)
    val DarkPrimaryContainer = Color(0xFF174955)
    val DarkOnPrimaryContainer = Color(0xFFD8ECEE)
    val DarkSecondary = Color(0xFF53A7B2)
    val DarkBackground = Color(0xFF0F1A1D)
    val DarkSurface = Color(0xFF162328)
    val DarkSurfaceVariant = Color(0xFF1E3036)
    val DarkOnSurface = Color(0xFFECF4F5)
    val DarkOnSurfaceVariant = Color(0xFFB7CDD1)
    val DarkOutline = Color(0xFF78949A)
    val DarkOutlineVariant = Color(0xFF344B52)
    val DarkSuccess = Color(0xFF72D5A6)
    val DarkSuccessContainer = Color(0xFF173B2B)
    val DarkOnSuccessContainer = Color(0xFFD1F3E4)
    val DarkExpense = Color(0xFFFF8D82)
    val DarkExpenseContainer = Color(0xFF4B201E)
    val DarkOnExpenseContainer = Color(0xFFFFDAD6)
    val DarkWarning = Color(0xFFFFD166)
    val DarkWarningContainer = Color(0xFF493716)
    val DarkOnWarningContainer = Color(0xFFFFE8B2)
    val DarkInfo = Color(0xFF9CC5FF)
    val DarkInfoContainer = Color(0xFF1E3553)
    val DarkOnInfoContainer = Color(0xFFD7E7FF)
}
